name: Node.js CI
on:
  pull_request:
    branches: [ "master" ]
  push:

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:

      - name: 'Checkout the repository'
        uses: actions/checkout@v6

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint TypeScript
        run: yarn run lint:ts

      - name: Compile TypeScript
        run: yarn run build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test
